// import "./App.css";
import Navbar from "./components/Navbar";

function App() {
	return (
		<div>
			
			<Navbar />
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxcxdddddddddddddddddd</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
			<div>vvcxc</div>
		</div>
	);
}

export default App;
